services:
  postgres:
    image: postgres:17
    container_name: pokemon_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: pokemon_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: